# Generated by Django 6.0.3 on 2026-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='qr_code_token',
            field=models.TextField(unique=True),
        ),
    ]
