# Generated by Django 6.0.3 on 2026-06-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_base_amount_booking_surge_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('expired', 'Expired'), ('partially_refunded', 'Partially Refunded')], default='pending_payment', max_length=20),
        ),
    ]
