# Generated by Django 6.0.3 on 2026-04-22 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('societies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied')], max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='bookings.booking')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='societies.society')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['society', 'scanned_at'], name='qr_validati_society_23a138_idx'), models.Index(fields=['guard', 'event_type', 'scanned_at'], name='qr_validati_guard_i_8842b0_idx')],
            },
        ),
    ]
