# Generated by Django 6.0.4 on 2026-04-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_scan_entry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_scan_exit",
            field=models.BooleanField(default=False),
        ),
    ]
