# Generated by Django 6.0.3 on 2026-04-22 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_can_scan_entry_user_can_scan_exit"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("join_request", "Join Request"),
                            ("join_approved", "Join Approved"),
                            ("join_rejected", "Join Rejected"),
                            ("slot_pending", "Slot Pending"),
                            ("slot_approved", "Slot Approved"),
                            ("slot_rejected", "Slot Rejected"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("message", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="accounts_us_user_id_587a4e_idx",
                    )
                ],
            },
        ),
    ]
