# Generated by Django 6.0.3 on 2026-04-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_usernotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="flat_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="floor_number",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
