# Generated by Django 6.0.3 on 2026-05-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_approval_notes_user_approval_status_and_more'),
        ('accounts', '0005_user_flat_number_user_floor_number'),
    ]

    operations = [
    ]
