# Generated by Django 6.0.3 on 2026-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260516_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approval_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='flat_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='floor_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
