# Generated by Django 6.0.3 on 2026-05-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_approval_notes_alter_user_flat_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temporary_password",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
