# Generated by Django 4.2.29 on 2026-04-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_checked_in_at_booking_checked_out_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guards', to='api.parkinglot'),
        ),
    ]
