# Generated by Django 4.2.29 on 2026-04-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_assigned_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('2-wheeler', '2-Wheeler'), ('4-wheeler', '4-Wheeler')], default='4-wheeler', max_length=20),
        ),
    ]
