# Generated by Django 6.0.3 on 2026-04-22 04:30

import apps.societies.models
import django.db.models.deletion
import uuid
import secrets
from django.conf import settings
from django.db import migrations, models


def backfill_join_codes(apps, schema_editor):
    Society = apps.get_model("societies", "Society")
    used = set()

    for society in Society.objects.order_by("id"):
        code = (society.join_code or "").strip().upper()
        if not code or code in used:
            code = secrets.token_hex(4).upper()
            while code in used:
                code = secrets.token_hex(4).upper()
            society.join_code = code
            society.save(update_fields=["join_code"])
        used.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ("societies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingslot",
            name="approval_notes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="parkingslot",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="approved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="parkingslot",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parkingslot",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="parkingslot",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="society",
            name="join_code",
            field=models.CharField(
                default=apps.societies.models.generate_society_join_code,
                max_length=12,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_join_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="society",
            name="join_code",
            field=models.CharField(
                default=apps.societies.models.generate_society_join_code,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="SocietyMembershipRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_membership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_requests",
                        to="societies.society",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("society", "user"),
                        name="unique_pending_membership_request_per_user_society",
                    )
                ],
            },
        ),
    ]
